# Usa una imagen base de Java (openjdk:17-alpine ya no existe en Docker Hub)
FROM eclipse-temurin:17-jdk-alpine
# Instala Maven (solo necesario si aún no tienes el archivo compilado)
RUN apk add --no-cache maven
# Directorio de trabajo dentro del contenedor
WORKDIR /app
COPY pom.xml /app
# Instalar las dependencias de Maven
RUN mvn dependency:go-offline -e
# Copiar el código fuente al contenedor
COPY . /app
# Exponer el puerto de la aplicación
EXPOSE 8080
# Comando para iniciar la aplicación con DevTools
CMD ./mvnw spring-boot:run -X
