spring.application.name=backend

app.security.username=admin
app.security.password=admin
app.security.role=ADMIN

# JWT
jwt.secret=${JWT_SECRET:73311767c9c1b84e5c86346eeb7e64e13adb9b914aea0cb18f70b30c27e9607a}
jwt.expiration=${JWT_EXPIRATION:86400000}

# cookie / cors
app.cookie.secure=${COOKIE_SECURE:true}
app.cookie.same-site=${COOKIE_SAME_SITE:Lax}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGINS:*}

# basic config
config.version=v${VERSION:1.0}

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_DB_HOST:localhost}:${SPRING_DATASOURCE_DB_PORT:5432}/${SPRING_DATASOURCE_DB_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# # Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# logging.level.org.hibernate.SQL=DEBUG
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
